/*
 * Copyright (c) 2026 Mica Technologies
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.micatechnologies.minecraft.launcher.utilities;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Covers {@link SingleInstanceLock#slowEquals(String, String)} — the check that
 * gates the loopback IPC channel a second launcher process uses to hand a
 * {@code mmcl://} deep link to an already-running instance. Any local process
 * on the same machine can connect to the loopback port, so this comparison is
 * the only thing standing between "same-UID process that can read the token
 * file" and "any process at all" being able to inject a play/join command into
 * a running launcher. Correctness matters more than the constant-time
 * property here (a local timing side-channel over a loopback socket read is a
 * stretch), but a functionally wrong comparison — one that accepts a mismatch,
 * or rejects a match — would either open or completely break the IPC gate.
 *
 * @since 3.0
 */
class SingleInstanceLockSlowEqualsTest
{
    @Test
    void acceptsIdenticalTokens()
    {
        assertTrue( SingleInstanceLock.slowEquals( "abc123", "abc123" ) );
    }

    @Test
    void rejectsDifferentTokensOfSameLength()
    {
        assertFalse( SingleInstanceLock.slowEquals( "abc123", "abc124" ) );
    }

    @Test
    void rejectsTokensOfDifferentLength()
    {
        assertFalse( SingleInstanceLock.slowEquals( "abc123", "abc1234" ) );
        assertFalse( SingleInstanceLock.slowEquals( "abc1234", "abc123" ) );
    }

    @Test
    void rejectsWhenEitherArgumentIsNull()
    {
        assertFalse( SingleInstanceLock.slowEquals( null, "abc123" ) );
        assertFalse( SingleInstanceLock.slowEquals( "abc123", null ) );
        assertFalse( SingleInstanceLock.slowEquals( null, null ) );
    }

    @Test
    void isCaseSensitive()
    {
        // Tokens are hex-encoded random bytes generated by the server; a case-folding
        // comparison would widen the effective token space an attacker needs to guess
        // (or, worse, silently accept a near-miss). Confirm no such folding happens.
        assertFalse( SingleInstanceLock.slowEquals( "ABC123", "abc123" ) );
    }

    @Test
    void emptyStringsAreEqualToEachOther()
    {
        assertTrue( SingleInstanceLock.slowEquals( "", "" ) );
    }

    @Test
    void comparesFullUtf8ByteLengthNotJustCharLength()
    {
        // A non-ASCII character's UTF-8 byte length can differ from its char count;
        // the comparison must operate over the same byte representation for both
        // sides or a byte-length mismatch could be missed. Not expected in a real
        // hex token, but the implementation compares getBytes(UTF_8) directly.
        assertTrue( SingleInstanceLock.slowEquals( "café", "café" ) );
        assertFalse( SingleInstanceLock.slowEquals( "café", "cafe" ) );
    }
}
