#!/usr/bin/env node
/*
 * Mica Minecraft Launcher — auto-translation tool
 *
 * Reads src/main/resources/lang/DisplayStrings.properties as the English
 * source-of-truth and writes DisplayStrings_<tag>.properties for each
 * locale in TARGET_LOCALES below.
 *
 * Usage:
 *   npm install        # one-time, fetches google-translate-api-x
 *   npm run translate            # incremental: only translate keys missing from each target
 *   npm run translate:force      # re-translate every key, overwriting existing values
 *   npm run translate:dry        # print what would change without writing any files
 *
 * The script is idempotent: existing translations are preserved on re-runs
 * unless --force is passed. It uses google-translate-api-x which hits the
 * free public Google Translate endpoint — rate-limited and unreliable for
 * very large batches, but fine for this 89-key × 16-locale workload.
 *
 * MessageFormat placeholders ({0}, {1}, ...) are protected from being
 * translated by swapping them for ASCII sentinels around each API call.
 *
 * Keep TARGET_LOCALES in sync with SupportedLocales.ENTRIES in
 * src/main/java/com/micatechnologies/minecraft/launcher/consts/localization/SupportedLocales.java
 */

import { translate } from 'google-translate-api-x';
import { readFile, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..');
const LANG_DIR = join(REPO_ROOT, 'src', 'main', 'resources', 'lang');
const SOURCE_FILE = join(LANG_DIR, 'DisplayStrings.properties');

const TARGET_LOCALES = [
    { tag: 'es',    googleCode: 'es',     name: 'Spanish' },
    { tag: 'fr',    googleCode: 'fr',     name: 'French' },
    { tag: 'de',    googleCode: 'de',     name: 'German' },
    { tag: 'pt-BR', googleCode: 'pt',     name: 'Portuguese (Brazil)' },
    { tag: 'it',    googleCode: 'it',     name: 'Italian' },
    { tag: 'ru',    googleCode: 'ru',     name: 'Russian' },
    { tag: 'ja',    googleCode: 'ja',     name: 'Japanese' },
    { tag: 'ko',    googleCode: 'ko',     name: 'Korean' },
    { tag: 'zh-CN', googleCode: 'zh-CN',  name: 'Simplified Chinese' },
    { tag: 'zh-TW', googleCode: 'zh-TW',  name: 'Traditional Chinese' },
    { tag: 'ar',    googleCode: 'ar',     name: 'Arabic' },
    { tag: 'hi',    googleCode: 'hi',     name: 'Hindi' },
    { tag: 'nl',    googleCode: 'nl',     name: 'Dutch' },
    { tag: 'pl',    googleCode: 'pl',     name: 'Polish' },
    { tag: 'tr',    googleCode: 'tr',     name: 'Turkish' },
    { tag: 'sv',    googleCode: 'sv',     name: 'Swedish' },
];

const FORCE = process.argv.includes('--force');
const DRY_RUN = process.argv.includes('--dry-run');
const DELAY_MS = 120;   // be polite to Google's free endpoint

function parseProperties(text) {
    // Returns { keysInOrder: [...], values: { key: value }, leadingComments: '...' }.
    // Mirrors the way java.util.Properties handles the file but preserves comment
    // ordering by capturing the leading comment block separately.
    const lines = text.split(/\r?\n/);
    const values = {};
    const keysInOrder = [];
    let leadingComments = '';
    let seenFirstKey = false;
    for (const rawLine of lines) {
        const line = rawLine;
        if (!seenFirstKey && (line.trim() === '' || line.trim().startsWith('#') || line.trim().startsWith('!'))) {
            leadingComments += line + '\n';
            continue;
        }
        if (line.trim() === '' || line.trim().startsWith('#') || line.trim().startsWith('!')) {
            continue;
        }
        const eq = line.indexOf('=');
        if (eq < 0) continue;
        const key = line.substring(0, eq).trim();
        const value = line.substring(eq + 1);   // do not trim — preserve trailing spaces
        if (!(key in values)) keysInOrder.push(key);
        values[key] = value;
        seenFirstKey = true;
    }
    return { keysInOrder, values, leadingComments };
}

function writeProperties(filePath, { keysInOrder, values, leadingComments }, sourceLocaleTag) {
    let out = leadingComments;
    if (!out.endsWith('\n')) out += '\n';
    out += `# Locale: ${sourceLocaleTag}\n`;
    out += `# Auto-generated by tools/i18n/translate-locales.js — re-run after\n`;
    out += `# DisplayStrings.properties changes to refresh translations. Use\n`;
    out += `# --force to overwrite existing values.\n\n`;
    for (const key of keysInOrder) {
        const v = values[key];
        if (v === undefined) continue;
        out += `${key}=${v}\n`;
    }
    return writeFile(filePath, out, 'utf8');
}

// MessageFormat placeholders ({0}, {1}, ...) and standalone format chars
// shouldn't be translated. Swap them for ASCII sentinels around each API
// call so Google doesn't reformat / translate them. The sentinels are
// chosen to be plain ASCII tokens unlikely to appear in any natural-
// language sentence.
function protectPlaceholders(text) {
    const placeholders = [];
    const protectedText = text.replace(/\{(\d+(?:,[^}]+)?)\}/g, (match) => {
        placeholders.push(match);
        return `__MMCL_PH${placeholders.length - 1}__`;
    });
    return { protectedText, placeholders };
}

function restorePlaceholders(translated, placeholders) {
    let restored = translated;
    for (let i = 0; i < placeholders.length; i++) {
        // Replace the sentinel (case-insensitive — some target languages
        // lowercase ALL-CAPS markers, e.g. Turkish).
        const sentinel = new RegExp(`__MMCL_PH${i}__`, 'gi');
        restored = restored.replace(sentinel, placeholders[i]);
    }
    return restored;
}

async function translateString(text, targetCode) {
    if (text === '' || text.trim() === '') return text;
    const { protectedText, placeholders } = protectPlaceholders(text);
    const result = await translate(protectedText, { from: 'en', to: targetCode });
    return restorePlaceholders(result.text, placeholders);
}

async function fileExists(path) {
    try { await access(path); return true; }
    catch { return false; }
}

async function main() {
    const sourceText = await readFile(SOURCE_FILE, 'utf8');
    const source = parseProperties(sourceText);
    console.log(`Source ${SOURCE_FILE}: ${source.keysInOrder.length} keys`);

    let totalCalls = 0;
    let totalSkipped = 0;
    let totalFailures = 0;

    for (const locale of TARGET_LOCALES) {
        const targetPath = join(LANG_DIR, `DisplayStrings_${locale.tag}.properties`);
        let existing = { keysInOrder: [], values: {}, leadingComments: '' };
        if (await fileExists(targetPath)) {
            existing = parseProperties(await readFile(targetPath, 'utf8'));
        }
        console.log(`\n→ ${locale.name} (${locale.tag})  [existing: ${existing.keysInOrder.length} keys]`);
        const merged = {
            keysInOrder: source.keysInOrder.slice(),
            values: {},
            leadingComments: source.leadingComments,
        };
        let translated = 0;
        let skipped = 0;
        let failed = 0;
        for (const key of source.keysInOrder) {
            const englishValue = source.values[key];
            const existingValue = existing.values[key];
            if (!FORCE && existingValue !== undefined && existingValue !== '') {
                merged.values[key] = existingValue;
                skipped++;
                totalSkipped++;
                continue;
            }
            if (DRY_RUN) {
                console.log(`  [dry] ${key} :: would translate "${englishValue.slice(0, 60)}..."`);
                merged.values[key] = englishValue;
                continue;
            }
            try {
                const result = await translateString(englishValue, locale.googleCode);
                merged.values[key] = result;
                translated++;
                totalCalls++;
            }
            catch (err) {
                console.warn(`  ✗ ${key} :: ${err.message || err}`);
                merged.values[key] = englishValue;   // fall back to English so the bundle is still loadable
                failed++;
                totalFailures++;
            }
            await new Promise((res) => setTimeout(res, DELAY_MS));
        }
        if (!DRY_RUN) {
            await writeProperties(targetPath, merged, locale.tag);
        }
        console.log(`  done: ${translated} translated, ${skipped} kept, ${failed} failed`);
    }

    console.log(`\nTotals: ${totalCalls} API calls, ${totalSkipped} kept, ${totalFailures} failed`);
    if (DRY_RUN) console.log(`(dry-run — no files written)`);
}

main().catch((err) => {
    console.error('FATAL:', err);
    process.exit(1);
});
