const enum ipcMessageNames {
  GIVE_STORED_ACCOUNTS = 'GIVE_STORED_ACCOUNTS',
  LOGIN_MS = 'LOGIN_MS',
  LOGOUT = 'LOGOUT',
  GET_STORED_ACCOUNTS = 'GET_STORED_ACCOUNTS',
  WINDOW_MINIMIZE = 'WINDOW_MINIMIZE',
  WINDOW_MAXIMIZE = 'WINDOW_MAXIMIZE',
  WINDOW_CLOSE = 'WINDOW_CLOSE',
  LOAD_SETTINGS = 'LOAD_SETTINGS',
  SAVE_SETTINGS = 'SAVE_SETTINGS',
}

export default ipcMessageNames;
