/*
 * Copyright (c) 2021 Mica Technologies
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.micatechnologies.minecraft.launcher.consts;

import java.io.File;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;

/**
 * Class of constants related to local file paths and storage for the application.
 * <p>
 * NOTE: This class should NOT contain display strings that are visible to the end-user. All localizable strings MUST be
 * stored and retrieved using {@link com.micatechnologies.minecraft.launcher.consts.localization.LocalizationManager}.
 *
 * @author Mica Technologies
 * @version 1.0
 * @since 2.0
 */
public class LocalPathConstants
{
    /**
     * The absolute file path to the application local storage folder when the application is operating in client mode.
     *
     * @since 1.0
     */
    public static final String CLIENT_MODE_LAUNCHER_FOLDER_PATH = System.getProperty( "user.home" ) +
            File.separator +
            "." +
            LauncherConstants.LAUNCHER_APPLICATION_NAME_TRIMMED;

    /**
     * The absolute file path to the application local storage folder when the application is operating in server mode.
     *
     * @since 1.0
     */
    public static final String SERVER_MODE_LAUNCHER_FOLDER_PATH = Paths.get( "" ).toAbsolutePath().toString();

    /**
     * Relative path to the application configuration folder within the application folder.
     *
     * @since 1.0
     */
    public static final String CONFIG_FOLDER = File.separator + "config";

    /**
     * Relative path to the application metadata folder within the application folder.
     *
     * @since 1.0
     */
    public static final String METADATA_FOLDER = File.separator + "metadata";

    /**
     * Relative path to the installed mod packs folder within the application folder.
     *
     * @since 1.0
     */
    public static final String MODPACK_FOLDER = File.separator + "installs";

    /**
     * Relative path to the log folder within the application folder.
     *
     * @since 1.0
     */
    public static final String LOG_FOLDER = File.separator + "logs";

    /**
     * Relative path to the runtime install folder within the application folder.
     *
     * @since 1.0
     */
    public static final String RUNTIME_FOLDER = File.separator + "runtime";

    /**
     * The date format used in the file name for logs generated by the application.
     *
     * @since 1.0
     */
    public static final SimpleDateFormat LOG_FILE_NAME_DATE_FORMAT = new SimpleDateFormat( "yyyy-MM-dd--HH-mm-ss" );

    /**
     * The name of the file used to store the client token.
     *
     * @since 1.0
     */
    public static final String CLIENT_TOKEN_FILE_NAME = File.separator + "client.mica";

    /**
     * The name of the file used to store the remembered user account (if remember option is enabled)
     *
     * @since 1.0
     */
    public static final String AUTH_ACCOUNT_REMEMBERED_FILE_NAME = File.separator + "player.mica";

    /**
     * The name of the file used to store the launcher update information from the launcher releases API.
     *
     * @since 1.0
     */
    public static final String LAUNCHER_UPDATE_INFO_FILE_NAME = File.separator + "update.mica";

    /**
     * File extension of Minecraft manifests that are stored locally.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_MANIFEST_LOCAL_FILE_EXTENSION = ".manifest";

    /**
     * The name of the file used to store the Minecraft version manifest
     *
     * @since 1.0
     */
    public static final String MINECRAFT_VERSION_MANIFEST_FILE_NAME = File.separator +
            "version" +
            MINECRAFT_MANIFEST_LOCAL_FILE_EXTENSION;

    /**
     * The mod pack relative path where assets are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_FOLDER = "assets";

    /**
     * Launcher-root relative folder for cross-modpack shared data. Currently only houses
     * shared assets; reserved for future shared resources (e.g. common libraries) if the
     * de-duplication is extended.
     *
     * @since 3.2
     */
    public static final String SHARED_FOLDER = File.separator + "shared";

    /**
     * Subfolder name appended after {@link #SHARED_FOLDER} for shared MC assets.
     *
     * @since 3.2
     */
    public static final String MINECRAFT_ASSET_SUBFOLDER = File.separator + MINECRAFT_ASSET_RELATIVE_FOLDER;

    /**
     * The mod pack relative path where asset indexes are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_INDEXES_FOLDER = MINECRAFT_ASSET_RELATIVE_FOLDER +
            File.separator +
            "indexes";

    /**
     * The mod pack relative path where asset objects are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_OBJECTS_FOLDER = MINECRAFT_ASSET_RELATIVE_FOLDER +
            File.separator +
            "objects";

    /**
     * The mod pack relative path where the legacy "virtual" flat asset tree lives. Pre-1.7
     * Minecraft (and any index marked {@code virtual: true}) reads assets by their virtual
     * name (e.g. {@code sound/random/click.ogg}) rather than by SHA-1, so we materialize a
     * flat copy of the hashed objects under this folder per asset-index id and point
     * {@code --assetsDir} at it.
     *
     * @since 3.2
     */
    public static final String MINECRAFT_ASSET_RELATIVE_VIRTUAL_FOLDER = MINECRAFT_ASSET_RELATIVE_FOLDER +
            File.separator +
            "virtual";

    /**
     * The mod pack relative path used by indexes marked {@code map_to_resources: true}
     * (1.6.x — assets are copied into the game directory's {@code resources/} folder).
     * Mostly historical; modern packs don't use this.
     *
     * @since 3.2
     */
    public static final String MINECRAFT_RESOURCES_FOLDER = "resources";

    /**
     * The name of the file used to store the Minecraft library manifest
     *
     * @since 1.0
     */
    public static final String MINECRAFT_LIBRARY_MANIFEST_FILE_NAME = "libraries" +
            MINECRAFT_MANIFEST_LOCAL_FILE_EXTENSION;

    /**
     * Name of the bin folder in mod pack installation folders.
     *
     * @since 1.0
     */
    public static final String MOD_PACK_BIN_FOLDER_NAME = "bin";

    /**
     * File extension of a Java .jar file.
     *
     * @since 1.0
     */
    public static final String JAR_FILE_EXTENSION = ".jar";

    /**
     * File extension of a launcher log file.
     *
     * @since 1.0
     */
    public static final String LOG_FILE_EXTENSION = ".log";

}
