/*
 * Copyright (c) 2021 Mica Technologies
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.micatechnologies.minecraft.launcher.consts;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;

/**
 * Class of constants related to local file paths and storage for the application.
 * <p>
 * NOTE: This class should NOT contain display strings that are visible to the end-user. All localizable strings MUST be
 * stored and retrieved using {@link com.micatechnologies.minecraft.launcher.consts.localization.LocalizationManager}.
 *
 * @author Mica Technologies
 * @version 1.0
 * @since 2.0
 */
public class LocalPathConstants
{
    /**
     * The absolute file path to the launcher's local storage folder.
     *
     * @since 1.0
     */
    public static final Path LAUNCHER_FOLDER_PATH = Path.of( System.getProperty( "user.home" ), "." +
            LauncherConstants.LAUNCHER_APPLICATION_NAME_TRIMMED );

    /**
     * The absolute file path to the launcher's configuration folder (within {@link #LAUNCHER_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path CONFIG_FOLDER_PATH = LAUNCHER_FOLDER_PATH.resolve( "config" );

    /**
     * The absolute file path to the launcher's installed games folder (within {@link #LAUNCHER_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path INSTALLS_FOLDER_PATH = LAUNCHER_FOLDER_PATH.resolve( "installs" );

    /**
     * The absolute file path to the launcher's logs folder (within {@link #LAUNCHER_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path LOGS_FOLDER_PATH = LAUNCHER_FOLDER_PATH.resolve( "logs" );

    /**
     * The absolute file path to the runtime download and installation folder (within {@link #LAUNCHER_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path RUNTIMES_FOLDER_PATH = LAUNCHER_FOLDER_PATH.resolve( "runtimes" );

    /**
     * The absolute file path to the runtime download and installation folder (within {@link #LAUNCHER_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path MC_VERSION_MANIFESTS_FOLDER_PATH = LAUNCHER_FOLDER_PATH.resolve( "mc-versions-manifests" );

    /**
     * The absolute file path of the file used to store the client token (within {@link #CONFIG_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path CLIENT_TOKEN_FILE_PATH = CONFIG_FOLDER_PATH.resolve( "client.tok" );

    /**
     * The absolute file path of the file used to store the saved authentication account (within {@link
     * #CONFIG_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path SAVED_AUTH_ACCOUNT_FILE_PATH = CONFIG_FOLDER_PATH.resolve( "player.tok" );

    /**
     * The absolute file path of the file used to store the launcher update information from the launcher releases API
     * (within {@link #CONFIG_FOLDER_PATH}).
     *
     * @since 1.0
     */
    public static final Path LAUNCHER_UPDATE_INFO_FILE_PATH = CONFIG_FOLDER_PATH.resolve( "updateInfo.json" );

    /**
     * File extension of Minecraft manifests that are stored locally.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_MANIFEST_LOCAL_FILE_EXTENSION = ".manifest";

    /**
     * The name of the file used to store the Minecraft version manifest
     *
     * @since 1.0
     */
    public static final String MINECRAFT_VERSIONS_MANIFEST_FOLDER_NAME = File.separator + "versions";

    /**
     * The mod pack relative path where assets are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_FOLDER = "assets";

    /**
     * The date format used in the file name for logs generated by the application.
     *
     * @since 1.0
     */
    public static final SimpleDateFormat LOG_FILE_NAME_DATE_FORMAT = new SimpleDateFormat( "yyyy-MM-dd--HH-mm-ss" );

    /**
     * The mod pack relative path where asset indexes are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_INDEXES_FOLDER = MINECRAFT_ASSET_RELATIVE_FOLDER +
            File.separator +
            "indexes";

    /**
     * The mod pack relative path where asset objects are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_OBJECTS_FOLDER = MINECRAFT_ASSET_RELATIVE_FOLDER +
            File.separator +
            "objects";

    /**
     * The name of the file used to store the Minecraft library manifest
     *
     * @since 1.0
     */
    public static final String MINECRAFT_LIBRARY_MANIFEST_FILE_NAME = "libraries" +
            MINECRAFT_MANIFEST_LOCAL_FILE_EXTENSION;

    /**
     * Name of the bin folder in mod pack installation folders.
     *
     * @since 1.0
     */
    public static final String MOD_PACK_BIN_FOLDER_NAME = "bin";

    /**
     * File extension of a Java .jar file.
     *
     * @since 1.0
     */
    public static final String JAR_FILE_EXTENSION = ".jar";

    /**
     * File extension of a launcher log file.
     *
     * @since 1.0
     */
    public static final String LOG_FILE_EXTENSION = ".log";

}
