/*
 * Copyright (c) 2020 Mica Technologies
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.micatechnologies.minecraft.forgelauncher.consts;

import com.micatechnologies.minecraft.forgelauncher.utilities.annotations.ClientAndServer;

import java.io.File;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;

/**
 * Class of constants related to local file paths and storage for the application.
 *
 * @author Mica Technologies
 * @version 1.0
 * @editors hawka97
 * @creator hawka97
 * @since 2.0
 */
@ClientAndServer
public class LocalPathConstants
{
    /**
     * The absolute file path to the application local storage folder when the application is operating in client mode.
     *
     * @since 1.0
     */
    public static final String CLIENT_MODE_LAUNCHER_FOLDER_PATH =
            System.getProperty( "user.home" ) + File.separator + "." +
                    LauncherConstants.LAUNCHER_APPLICATION_NAME_TRIMMED;

    /**
     * The absolute file path to the application local storage folder when the application is operating in server mode.
     *
     * @since 1.0
     */
    public static final String SERVER_MODE_LAUNCHER_FOLDER_PATH = Paths.get( "" ).toAbsolutePath().toString();


    /**
     * Relative path to the application configuration folder within the application folder.
     *
     * @since 1.0
     */
    public static final String CONFIG_FOLDER = File.separator + "config";

    /**
     * Relative path to the installed modpacks folder within the application folder.
     *
     * @since 1.0
     */
    public static final String MODPACK_FOLDER = File.separator + "installs";

    /**
     * Relative path to the log folder within the application folder.
     *
     * @since 1.0
     */
    public static final String LOG_FOLDER = File.separator + "logs";

    /**
     * Relative path to the runtime install folder within the application folder.
     *
     * @since 1.0
     */
    public static final String RUNTIME_FOLDER = File.separator + "runtime";

    /**
     * The date format used in the file name for logs generated by the application.
     *
     * @since 1.0
     */
    public static final SimpleDateFormat LOG_FILE_NAME_DATE_FORMAT = new SimpleDateFormat( "yyyy-MM-dd--HH-mm-ss" );

    /**
     * The name of the file used to store the client token.
     *
     * @since 1.0
     */
    public static final String CLIENT_TOKEN_FILE_NAME = File.separator + "client.mica";

    /**
     * The name of the file used to store the remembered user account (if remember option is enabled)
     *
     * @since 1.0
     */
    public static final String AUTH_ACCOUNT_REMEMBERED_FILE_NAME = File.separator + "player.mica";

    /**
     * The name of the file used to store the Minecraft version manifest
     *
     * @since 1.0
     */
    public static final String MINECRAFT_VERSION_MANIFEST_FILE_NAME = File.separator + "version.manifest";

    /**
     * The mod pack relative path where assets are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_FOLDER = "assets";

    /**
     * The mod pack relative path where asset indexes are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_INDEXES_FOLDER =
            MINECRAFT_ASSET_RELATIVE_FOLDER + File.separator + "indexes";

    /**
     * The mod pack relative path where asset objects are stored.
     *
     * @since 1.0
     */
    public static final String MINECRAFT_ASSET_RELATIVE_OBJECTS_FOLDER =
            MINECRAFT_ASSET_RELATIVE_FOLDER + File.separator + "objects";

}
