name: Build Packages

on:
  push:
    branches-ignore:
      - 'launcher_rewrite_work'

jobs:

  pkg_win:

    name: Build Windows Package(s)

    runs-on: windows-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set path for Wix Toolset
        env:
          WIX_PATH: ${{ env.wix }}
        run: echo "$env:WIX_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Windows package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: windows-pkg-output
          path: |
            packaging
            !packaging/assets

  pkg_mac:

    name: Build macOS Package(s)

    runs-on: macos-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Import Code Signing Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          p12-file-base64: ${{ secrets.MAC_CS_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.MAC_CS_CERTIFICATES_P12_PASSWORD }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload macOS package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: mac-pkg-output
          path: |
            packaging
            !packaging/assets

  pkg_lnx:

    name: Build Linux Package(s)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build tools
        run: sudo apt install -y dpkg rpm

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Linux package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: linux-pkg-output
          path: |
            packaging
            !packaging/assets
