name: Build Packages

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:

  pkg_win:

    name: Build Windows Package(s)

    runs-on: windows-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set path for candle and light
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Windows package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-pkg-output
          path: |
            packaging/*.exe
            packaging/*.msi
            target/*-jar-with-dependencies.jar

  pkg_mac:

    name: Build macOS Package(s)

    runs-on: macos-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Import Code Signing Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MAC_CS_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.MAC_CS_CERTIFICATES_P12_PASSWORD }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload macOS package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mac-pkg-output
          path: |
            packaging/*.dmg
            packaging/*.pkg
            target/*-jar-with-dependencies.jar

  pkg_lnx:

    name: Build Linux Package(s)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
          java-package: jdk+fx

      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ./jdk
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build tools
        run: sudo apt install -y dpkg rpm

      - name: Build and package with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Linux package(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-pkg-output
          path: |
            packaging/*.rpm
            packaging/*.deb
            packaging/*.changes
            packaging/*.AppImage
            target/*-jar-with-dependencies.jar
